### ISSUE TITLE
IE11 doesn't support Promise

### ISSUE THREAD

**Issue by francoislg** [coveo/coveo.analytics.js#151]
It throws 

```
SCRIPT5009: 'Promise' is undefined; 
File: coveoua.js, Line: 1, Column: 10303
```

We should probably ship this with a polyfill.

**Comment by pastjean** [comment]
I thought the pollyfill was included :/

**Comment by pastjean** [comment]
Well i just looked in the webpack file and it is not, this is a bug indeed. Can you fix that ?
