### ISSUE TITLE
Metrics not displayed in reports for the customData parameter

### ISSUE THREAD

**Issue by sgeric** [coveo/coveo.analytics.js#329]
Hi, 
I'm trying to create a metric for the click events on CoveoResult item, but i have some issues, always getting 0 counts. 

On click event, I can see custom data value on networks tab in the browser:
![image](https://user-images.githubusercontent.com/73079483/156594295-828d7a5b-8e45-48da-aa5f-23c39d94f1ea.png)
I also created dimension in Dimensions:
![image](https://user-images.githubusercontent.com/73079483/156594610-ced5893e-0f7f-4b63-9da7-8bf24e80b3dd.png)

But with this metric and filter, always getting 0 count. 
![image](https://user-images.githubusercontent.com/73079483/156594913-8c7d4e0b-cde3-4585-a9a2-b92fbac9f667.png)

Thanks in advance.

**Comment by fvanham-coveo** [comment]
I'm closing this issue, as it's not related to the tracking library itself. For Coveo product related questions there are other support channels.
